<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="QuickTest Professional" productVer="10.00" os="" host="LAPTOP-A8N0LH29"><DocLocation><![CDATA[C:\Users\li\Desktop\测试脚本\RegisterSuccessTest]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[RegisterSuccessTest]]></DName>
<Res><![CDATA[Res5]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Login_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:22]]></Time>
<TimeTick>1546484842</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Login_4.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[344, 186]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:22]]></Time>
<TimeTick>1546484842</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Login_4.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Login_4.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[411, 180]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:23]]></Time>
<TimeTick>1546484843</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Login_4.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login_4.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["213"]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:24]]></Time>
<TimeTick>1546484844</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="14" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Login_4.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login_4.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[396, 232]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:25]]></Time>
<TimeTick>1546484845</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="16" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Login_4.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Login_4.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["321323"]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:25]]></Time>
<TimeTick>1546484845</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="18" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Login_4.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Login_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Login_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:40]]></Time>
<TimeTick>1546484860</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[385, 316]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:40]]></Time>
<TimeTick>1546484860</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="22" status="Warning" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Login_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Login_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Login_2" (of class Window). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:40]]></Time>
<TimeTick>1546484860</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Login_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>simclass = HwndWrapper[Timeline.exe;;2ae93698-c6de-49f7-b948-1189a5c1621b]<br>regexpwndtitle = Login<br>regexpwndclass = HwndWrapper[Timeline.exe;;2ae93698-c6de-49f7-b948-1189a5c1621b]<br>is owned window = 0<br>is child window = 0<br>]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:40]]></Time>
<TimeTick>1546484860</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" status="Warning" nType="Description" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Login_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="23" status="Failed" nType="Run Error" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Login_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:40]]></Time>
<TimeTick>1546484860</TimeTick>
<NodeArgs eType="General" icon="7" nRep="25" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="21" status="Failed" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Login_2]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2019/1/3 - 11:07:22" eTime="2019/1/3 - 11:07:40" passed="0" failed="1" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[RegisterSuccessTest Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2019/1/3 - 11:07:40]]></Time>
<TimeTick>1546484860</TimeTick>
<NodeArgs eType="General" icon="8" nRep="28" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2019/1/3 - 11:07:20" eTime="2019/1/3 - 11:07:40" passed="0" failed="1" warnings="2" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test RegisterSuccessTest Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>